[theme]
primaryColor = "#635BFF"  # Vibrant purple for buttons and highlights
backgroundColor = "#FFFFFF"  # White background
secondaryBackgroundColor = "#F0F2F6"  # Slightly lighter gray for cards
textColor = "#262730"  # Dark gray text for contrast
font = "sans serif"  # Clean, modern font

[server]
runOnSave = true  # Turn off automatic rerun on save
headless = true  # Enable browser UI
enableCORS = true  # Allow cross-origin requests
port = 8501# Change the default port if needed

fileWatcherType = "none"

[ui]
hideTopBar = true  # Hide the default Streamlit top bar

[logger]
level = "info"
