[theme]
primaryColor = "#635BFF"  # Vibrant purple for buttons and highlights
backgroundColor = "#FFFFFF"  # White background
secondaryBackgroundColor = "#F0F2F6"  # Slightly lighter gray for cards
textColor = "#262730"  # Dark gray text for contrast
font = "sans serif"  # Clean, modern font

[server]
headless = false  # Enable browser UI
enableCORS = true  # Allow cross-origin requests
enableXsrfProtection = true  # Protect against CSRF attacks
# Disable file watcher for torch
enableStaticServing = true
fileWatcherType = "none"

[ui]
hideTopBar = true  # Hide the default Streamlit top bar

[logger]
level = "info"
